### ISSUE TITLE
Any idea how to run it in a Cloudflare Worker ?

### ISSUE THREAD

**Issue by LilaRest** [aiji42/prisma-datapoxy-server#30]
Hi ! I'm trying to run a minimal Prisma data proxy in a Cloudflare Worker and was considering doing this using this project. 
Does anyone has already achieved something similar or have informations that could help me ?
Thanks :)

**Comment by eleven-am** [comment]
This project requires the node runtime. To function and thus can not work on cloud flare workers however you can host it on gcp or Vercel and then connect to it in your workers

**Comment by LilaRest** [comment]
> This project requires the node runtime. To function and thus can not work on cloud flare workers however you can host it on gcp or Vercel and then connect to it in your workers

Thanks for your answer, I realized that few hours after posting this issue ^^
